stages:
 - testbackend
 - testfrontend
 - deploy

testbackend:
 stage: testbackend
 tags:
  - Backend
 script:
  - cd backend/server
  - node -c index.js

testfrontend:
 stage: testfrontend
 tags:
  - Frontend
 script:
  - cd frontend/eventlocator/src
  - npm build

deploy:
 stage: deploy
  - git pull origin master
  - sudo systemctl restart eventlocator-frontend
  - sudo systemctl restart eventlocator-backend
